# Site settings
title: Tino's AI
email: fortunato.nucera@icloud.com
description: > # this means to ignore newlines in the text below
        This blog wants to be a place where I share all the interesting machine learning techniques I come across.
        I haven't decided yet on what kind of level of detail I would like to offer, but I will try to provide reference where those
        are needed and, if possible, code snippets. 
        The reason why I have decided to start this adventure is the disappointment in the publishing format on Medium. I have written there,
        I like a lot of writers there, but when statistics and probability are involved, being able to write math inline via MathJax is essential. 
        GitHub Pages allows that and here I am!
url: "http://tinosai.github.io" # the base hostname & protocol for your site
github_username:  tinosai
linkedin_username: fortunato-nucera-5b35ba111

# Build settings
markdown: kramdown
exclude: ['*.Rmd']
