# Site settings
title: Tino's AI
email: fortunato.nucera@icloud.com
description: > # this means to ignore newlines in the text below
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://tinosai.github.io" # the base hostname & protocol for your site
github_username:  tinosai
linkedin_username: fortunato-nucera-5b35ba111

# Build settings
markdown: kramdown
exclude: ['*.Rmd']
